### ISSUE TITLE
ValueError while running the code

### ISSUE THREAD

**Issue by Sadat75** [WeiWang-WYS/IRSconfigurationDRL#1]
I have been trying to run the provided code on tensorflow version (2.4.1). But every time I am getting the error provided below:

 **ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 8), found shape=(None, 1, 8)**

Please provide me a solution for this. Thank you.

**Comment by aryatahlil** [comment]
I have the same problem. could u solve that?

**Comment by WeiWang-WYS** [comment]
You might try to reshape Input 0 from (None, 1, 8) to (None, 8).

**Comment by aryatahlil** [comment]
thank you so much for your response.Would you please help me to figure out which line of code should be changed? if you see the link that I mentioned before, another student had the same problem and maybe other students will have too.if you help me or submit another branch on Github, it would be so helpful and we'll be so grateful.

P.s: may it be related to your Tensorflow version?     On Wednesday, August 10, 2022 at 06:36:09 AM PDT, WeiWang-WYS ***@***.***> wrote:  
 
 


You might try to reshape Input 0 from (None, 1, 8) to (None, 8).

**Comment by aryatahlil** [comment]
Would you please help me to figure out which line of code should be changed?  
if you submit another branch it would be so helpful for me and other students in the future.
PS: may it be related to your Tensorflow version?

**Comment by WeiWang-WYS** [comment]
My Tensorflow version is 2.3.0. I might need some time to figure out the error that appears in your version.

**Comment by aryatahlil** [comment]
I used TensorFlow 2.3 and the problem was solved. the error just is showing as a warning :
WARNING:tensorflow:Model was constructed with shape (None, 8) for input Tensor("InputA:0", shape=(None, 8), dtype=float32), but it was called on an input with incompatible shape (None, 1, 8).

but in newer TensorFlow, it doesn't work at all 
Thank u so much

**Comment by WeiWang-WYS** [comment]
> I have been trying to run the provided code on tensorflow version (2.4.1). But every time I am getting the error provided below:
> 
> **ValueError: Input 0 is incompatible with layer model_2: expected shape=(None, 8), found shape=(None, 1, 8)**
> 
> Please provide me a solution for this. Thank you.

Hi, the code is updated, kindly test it on your end.

**Comment by Sadat75** [comment]
Thank you!

**Comment by Amrican10** [comment]
I am trying to run the code but got an error in this line:
Pos_UE = np.array([[np.random.rand(1) * 10, np.random.rand(1) * 10, 1.5], [np.random.rand(1) * 10, np.random.rand(1) * 10, 1.5]], dtype = float)

setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

Any help for a solution? thanks!
